const KEY="nicole0_description_overrides_v1";
const $=q=>document.querySelector(q), esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const defs={
 constellation:{file:"constellations.json",label:"星座",fields:[
  ["legacy_story","従来の概要","full"],["explanation.science","天文学",""],["explanation.myth","神話・由来",""]]},
 star:{file:"stars.json",label:"恒星",fields:[["highlight","ひとこと","full"],["explanation.overview","概要",""],["explanation.observing","観測のポイント",""],["explanation.science","天文学的な見どころ",""],["explanation.history","歴史・名前",""]]},
 dso:{file:"deep-sky.json",label:"深宇宙天体",fields:[["highlight","ひとこと","full"],["explanation.overview","概要",""],["explanation.observing","観測のポイント",""],["explanation.science","天文学的な見どころ",""],["explanation.history","歴史・名前",""]]},
 planet:{file:"planets.json",label:"惑星",fields:[["highlight","ひとこと","full"],["explanation.overview","概要",""],["explanation.observing","観測のポイント",""],["explanation.science","天文学的な見どころ",""],["explanation.history","歴史・名前",""]]}
};
let db={},manifest=null,currentKind="constellation",currentId=null,overrides=loadOverrides();
function loadOverrides(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');return d&&typeof d==='object'?{schema:"nicole0-description-overrides-v1",updatedAt:d.updatedAt||null,items:d.items&&typeof d.items==='object'?d.items:{}}:{schema:"nicole0-description-overrides-v1",items:{}}}catch(e){return{schema:"nicole0-description-overrides-v1",items:{}}}}
function saveOverrides(){overrides.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(overrides));window.dispatchEvent(new StorageEvent('storage',{key:KEY,newValue:JSON.stringify(overrides)}))}
function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[k],o)??""}
function setPath(o,path,val){const ks=path.split('.');let q=o;for(let i=0;i<ks.length-1;i++)q=q[ks[i]]||(q[ks[i]]={});q[ks.at(-1)]=val}
function clone(v){return JSON.parse(JSON.stringify(v))}
function merge(t,p){for(const[k,v]of Object.entries(p||{})){if(v&&typeof v==='object'&&!Array.isArray(v)){if(!t[k]||typeof t[k]!=='object'||Array.isArray(t[k]))t[k]={};merge(t[k],v)}else t[k]=v}return t}
function key(kind,id){return `${kind}:${id}`}
function sourceItem(kind,id){return (db[kind]||[]).find(x=>String(x.id)===String(id))}
function effectiveItem(kind,id){const o=clone(sourceItem(kind,id));const p=overrides.items[key(kind,id)];if(p)merge(o,p);return o}
function itemName(x){return x?.name?.ja_full||x?.name?.ja||x?.name?.en||x?.id||""}
function renderList(){const q=$('#search').value.trim().toLowerCase(),arr=(db[currentKind]||[]).filter(x=>!q||(`${itemName(x)} ${x.id}`).toLowerCase().includes(q));$('#list').innerHTML=arr.map(x=>`<button class="item ${x.id===currentId?'active':''}" data-id="${esc(x.id)}"><b>${esc(itemName(x))}</b><div class="meta">${esc(x.id)}${overrides.items[key(currentKind,x.id)]?' / 編集済み':''}</div></button>`).join('');$('#list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectItem(b.dataset.id))}
function selectItem(id){currentId=id;const x=effectiveItem(currentKind,id),def=defs[currentKind];$('#itemTitle').textContent=itemName(x);$('#itemMeta').textContent=`${def.label} / ${id}`;$('#fields').innerHTML=def.fields.map(([path,label,cl])=>`<div class="field ${cl}"><label>${esc(label)}</label><textarea data-path="${path}">${esc(getPath(x,path))}</textarea></div>`).join('');$('#status').textContent=overrides.items[key(currentKind,id)]?'ローカル編集あり':'DBの初期値';renderList()}
function saveCurrent(){if(!currentId)return;const patch={};$('#fields [data-path]').forEach(el=>setPath(patch,el.dataset.path,el.value));overrides.items[key(currentKind,currentId)]=patch;saveOverrides();$('#status').textContent='保存しました。Nicole 2を再読み込みすると反映されます。';renderList()}
function resetCurrent(){if(!currentId)return;delete overrides.items[key(currentKind,currentId)];saveOverrides();selectItem(currentId);$('#status').textContent='この天体をDB初期値へ戻しました。'}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function editedCategory(){return (db[currentKind]||[]).map(x=>{const y=clone(x),p=overrides.items[key(currentKind,x.id)];if(p){merge(y,p);if(p.explanation&&y.explanation)delete y.explanation.raw_html}return y})}
async function boot(){manifest=await fetch('./manifest.json',{cache:'no-store'}).then(r=>r.json());$('#dbVersion').textContent=`DB v${manifest.database_version}`;for(const[k,d]of Object.entries(defs))db[k]=await fetch(`./data/${d.file}`,{cache:'no-store'}).then(r=>r.json());renderList();selectItem(db[currentKind][0]?.id);$('#status').textContent='準備完了'}
$('#kind').onchange=e=>{currentKind=e.target.value;currentId=null;renderList();selectItem(db[currentKind][0]?.id)};$('#search').oninput=renderList;$('#save').onclick=saveCurrent;$('#resetItem').onclick=resetCurrent;$('#exportPatch').onclick=()=>download(`Nicole0-description-overrides-${new Date().toISOString().slice(0,10)}.json`,overrides);$('#importPatch').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!d?.items||typeof d.items!=='object')throw Error('形式が違います');overrides={schema:'nicole0-description-overrides-v1',updatedAt:new Date().toISOString(),items:d.items};saveOverrides();renderList();if(currentId)selectItem(currentId);$('#status').textContent='差分を読み込みました'}catch(err){alert('読み込み失敗: '+err.message)}e.target.value=''};$('#resetAll').onclick=()=>{if(!confirm('ローカルで編集した解説をすべて消去しますか？'))return;overrides={schema:'nicole0-description-overrides-v1',items:{}};saveOverrides();renderList();if(currentId)selectItem(currentId);$('#status').textContent='全編集を初期値へ戻しました'};$('#downloadData').onclick=()=>download(defs[currentKind].file,editedCategory());
window.addEventListener('storage',e=>{if(e.key===KEY){overrides=loadOverrides();renderList();if(currentId)selectItem(currentId)}});boot().catch(e=>{$('#status').textContent='読込失敗: '+e.message;console.error(e)});
